name: "4 stepper motors can be connected, CNC controller."
board: "HYB_ESPA"
meta: 2025-04-20 CNC
stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 2
  pulse_us: 6
  disable_delay_us: 2
  segments: 12

kinematics:
  cartesian:

uart1:
  txd_pin: gpio.22
  rxd_pin: gpio.21
  baud: 115200
  mode: 8N1

axes:
  shared_stepper_disable_pin: gpio.25:high
  homing_runs: 2
  x:
    steps_per_mm: 400
    max_rate_mm_per_min: 2400.0
    acceleration_mm_per_sec2: 100.0
    max_travel_mm: 310.0
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 310.0
      feed_mm_per_min: 200
      seek_mm_per_min: 1000
      settle_ms: 200
      seek_scaler: 1.0
      feed_scaler: 1.0
    motor0:
      limit_all_pin: gpio.34:low
      hard_limits: true
      pulloff_mm: 0.5
      # x stepper slave mode, use z stepper parameters
      tmc_2208:
        step_pin: gpio.27
        direction_pin: gpio.26:low

        uart_num: 1
        addr: 0
        #en_spreadcycle : true
        r_sense_ohms: 0.110
        run_amps: 1.0
        hold_amps: 0.5
        microsteps: 16
        stallguard: 1
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: CoolStep
        homing_mode: CoolStep
        use_enable: false
        disable_pin: NO_PIN

  y:
    steps_per_mm: 400
    max_rate_mm_per_min: 2400.0
    acceleration_mm_per_sec2: 100.0
    max_travel_mm: 215.0
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 215.000
      feed_mm_per_min: 200.0
      seek_mm_per_min: 1000.0
      settle_ms: 200
      seek_scaler: 1.0
      feed_scaler: 1.0

    motor0:
      limit_all_pin: gpio.35:low
      hard_limits: true
      pulloff_mm: 0.5
      # y stepper slave mode, use z stepper parameters
      tmc_2208:
        step_pin: gpio.33
        direction_pin: gpio.32:high

        uart_num: 1
        addr: 0
        #en_spreadcycle : true
        r_sense_ohms: 0.110
        run_amps: 1.0
        hold_amps: 0.5
        microsteps: 16
        stallguard: 1
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: CoolStep
        homing_mode: CoolStep
        use_enable: false
        disable_pin: NO_PIN

  z:
    steps_per_mm: 400
    max_rate_mm_per_min: 2400.0
    acceleration_mm_per_sec2: 100.0
    max_travel_mm: 85.0
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 85.0
      feed_mm_per_min: 200.0
      seek_mm_per_min: 1000.0
      settle_ms: 200
      seek_scaler: 1.0
      feed_scaler: 1.0
    motor0:
      limit_all_pin: gpio.15:low
      #limit_neg_pin: gpio.15
      hard_limits: true
      pulloff_mm: 0.5
      tmc_2208:
        step_pin: gpio.14
        direction_pin: gpio.12:high

        uart_num: 1
        addr: 0
        #en_spreadcycle : true
        r_sense_ohms: 0.110
        run_amps: 1.0
        hold_amps: 0.5
        microsteps: 16
        stallguard: 1
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: CoolStep
        homing_mode: CoolStep
        use_enable: false
        disable_pin: NO_PIN

pwm:
  pwm_hz: 1000
  direction_pin: NO_PIN
  output_pin: gpio.2
  enable_pin: gpio.13
  disable_with_s0: true
  s0_with_disable: true
  spinup_ms: 1000
  spindown_ms: 1000
  tool_num: 0
  speed_map: 0=0.000% 1000=1.000% 30000=97.000%
  off_on_alarm: false

coolant:
  #flood_pin: gpio.13
  #mist_pin: gpio.13
  delay_ms: 1000

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
  

sdcard:
  cs_pin: gpio.05
  card_detect_pin: NO_PIN

start:
  must_home: false
  deactivate_parking: false
  check_limits: false

probe:
  pin: gpio.0:low
  check_mode_start: false
