M48
; DRILL file {KiCad 9.0.1-9.0.1-0~ubuntu24.04.1} date 2025-04-30T23:19:25+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-30T23:19:25+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1-9.0.1-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X6.215Y55.49
X6.215Y49.71
T2
X4.2Y30.65
X4.2Y22.65
M30
